### PR TITLE
fix: negative feedback class incorrect

### PR DESCRIPTION
**Pull request by sandangel**
Signed-off-by: San Nguyen <vinhsannguyen91@gmail.com>

### CODE REVIEW

**Comment by sandangel** [comment]
cc @willydouhard

**Comment by dokterbob** [comment]
@sandangel Thanks for the PR! 

Could you perhaps explain a bit about the issue (e.g. with a screenshot) and give steps how to replicate and possibly fix it?

**Comment by sandangel** [comment]
The feedback value is either 0 or 1.  It used to be -1, 0 or 1. We forgot to change the value here so the negative-feedback-on class was not applied correctly so we could not use it to style the button the way we want.

**Review by willydouhard — APPROVED** [review]

**Comment by willydouhard** [comment]
Nice catch!

**Pull request merged**
