### PR TITLE
feat: move frontend out of poetry scope

### LINKED ISSUE #276: Speed up the building time?
Was there any way to speed up the building time? I found it took too much time to build the wheel package, it tooks more than 30 minutes each time.

### PR DESCRIPTION
**Pull request by chenjuneking**
After a new release publish, I think it's a good time to move frontend out of the poetry scope to speed up the build time.

Close #276

### CODE REVIEW

**Comment by ramnes** [comment]
Yes, nice! I'd personally remove the `src/` folder because it adds a level for not much (although that's controversial) and also rename `chainlit/chainlit/` to `backend/chainlit/` so that it's clear that it's the backend code.

**Comment by chenjuneking** [comment]
> Yes, nice! I'd personally remove the `src/` folder because it adds a level for not much (although that's controversial) and also rename `chainlit/chainlit/` to `backend/chainlit/` so that it's clear that it's the backend code.

That's more clear, the changes has been commited.

**Comment by chenjuneking** [comment]
> I think an additional change is required on this [line](https://github.com/chenjuneking/chainlit/blob/feat/mv_frontend/.github/workflows/publish.yaml#L40). The readme is supposed to be copied to the chainlit python dir (for pypi and other stuff).
> 
> Also the latest release introduced conflicts it seems.
> 
> Good work!

Thanks for your remind, all the issues has been fixed.

**Comment by willydouhard** [comment]
Ill try this branch on my laptop before merging, since it has the potential to break a lot of things :)

**Comment by willydouhard** [comment]
Thank you for your contribution! We ended up merging https://github.com/Chainlit/chainlit/pull/343 which was inspired by your work! Closing this one :)

**Pull request closed without merging**
