### PR TITLE
1.2.0 Hotfix - Add get_element() to sql_alchemy.py

### PR DESCRIPTION
**Pull request by hayescode**
Solve #1345 

_P.S._ mypy is annoying

### CODE REVIEW

**Comment by dokterbob** [comment]
Arguably, this code never worked (well). Happy to have an implementation now!

Any chance for test coverage? E.g. using SQLite in a temp file, creating an element, then getting it?

**Comment by hayescode** [comment]
@dokterbob you're right it never existed and the recent refactoring in 1.2.0 uncovered this, which is good!

There should probably be robust tests for all data layers/methods for max robustness. This is not something I can (or should) do in the short term and this hot fix is needed to make 1.2.0 work for anyone using SQLAlchemyDataLayer, since currently we cannot upgrade due to this.

**Comment by dokterbob** [comment]
> @dokterbob you're right it never existed and the recent refactoring in 1.2.0 uncovered this, which is good!
> 
> There should probably be robust tests for all data layers/methods for max robustness. This is not something I can (or should) do in the short term and this hot fix is needed to make 1.2.0 work for anyone using SQLAlchemyDataLayer, since currently we cannot upgrade due to this.

You don't have to but seeing test coverage would nudge me to merge this PR immediately. We're currently considering a fixup release.

**Comment by smannathan** [comment]
I tried this fix in my local, custom persistence using SQLAlchemyDataLayer with no storage provider.

/project/threads - API is failing, does not return threads.

**Comment by hayescode** [comment]
> I tried this fix in my local, custom persistence using SQLAlchemyDataLayer with no storage provider.
> 
> /project/threads - API is failing, does not return threads.

@smannathan i tried to reproduce by removing storage client but everything works normally for me. Are you sure this is related to get_element()? You mention threads.

> You don't have to but seeing test coverage would nudge me to merge this PR immediately. We're currently considering a fixup release.

@dokterbob there don't seem to be tests for much, if any, data layers. It would of course be a good feature to add, but doesn't justify holding back a bug fix that prevents upgrade "for security reasons" when tests didn't exist before. It's basically asking for a feature, which to be completely honest, I'm not very motivated to invest time in given the dozens of outstanding feature requests to the dev team from the community (many are to return functionality we once had) that have been open for 3+ months. This started before your time, and you've done great work so far, but please understand it's unusual for me, a non-Literal employee, to get asked to add features when the actual company running this project has not done this or really even responded to the 350+ issues for months.

**Comment by smannathan** [comment]
> @smannathan i tried to reproduce by removing storage client but everything works normally for me. Are you sure this is related to get_element()? You mention threads.
> 
> >

Sorry, It is totally unrelated issue. 

/project/threads - browser fails handle the chat history if data is quiet large data. 
API is returning the data properly, for some reason, browser just ignores the large payload data with http 200.

**Comment by dokterbob** [comment]
> @dokterbob there don't seem to be tests for much, if any, data layers.

That's exactly what I'm hoping to change. We're hoping to fork the data layers out into a separate chainlit-community repo over the coming weeks. Before that happens, though, I want to have enough test coverage to be able to ensure what's there now is (mostly) working.

> It would of course be a good feature to add, but doesn't justify holding back a bug fix that prevents upgrade "for security reasons" when tests didn't exist before.

I'm holding back because I didn't have time to test manually and I only want to merge fixes which are tested to actually fix the issue (by someone else than the original author). As @smannathan suggests, this might not be the case here.

> It's basically asking for a feature, which to be completely honest, I'm not very motivated to invest time in given the dozens of outstanding feature requests to the dev team from the community (many are to return functionality we once had) that have been open for 3+ months.

That's why it's my priority now to make reviewing PR's as efficient as possible. Unit test coverage is one of the ways of getting us there; it allows accepting changes without having to manually test everything, or risking that we'll break arbitrary things on every release.

I'm sorry for your frustration. Open Source is frustrating some times (both for maintainers and contributors). I invite you to use your frustration to work with us to make things better!

> This started before your time, and you've done great work so far, but please understand it's unusual for me, a non-Literal employee, to get asked to add features when the actual company running this project has not done this or really even responded to the 350+ issues for months.

It's perfectly normal for FOSS contributors to be asked to make changes and/or extensions to PR's. In fact, many popular FOSS packages have rigorous standards as to what (kinds of) PR's they're willing to accept. I know there's pain in setting such standards, but I personally want to be able to rely on chainlit in production -- and this really is part of getting us there.

**Comment by hayescode** [comment]
> > there don't seem to be tests for much, if any, data layers.
> 
> That's exactly what I'm hoping to change. We're hoping to fork the data layers out into a separate chainlit-community repo over the coming weeks. Before that happens, though, I want to have enough test coverage to be able to ensure what's there now is (mostly) working.
> 

@dokterbob makes sense. I do think creating and sharing documentation and a structure for tests with the community would be helpful. Like for this sqlite idea, which is a good one, it would be nice if that existed with dummy data for all of the tables. Then I think the community would be more likely to create tests tbh.

> > It would of course be a good feature to add, but doesn't justify holding back a bug fix that prevents upgrade "for security reasons" when tests didn't exist before.
> 
> I'm holding back because I didn't have time to test manually and I only want to merge fixes which are tested to actually fix the issue (by someone else than the original author).
> 

Ideally yes, but for what it's worth i made this SQLAlchemy data layer in the first place (and therefore I caused this problem I guess!) and I tested it the same way as before. Code is pretty straightforward imo, and this `get_element()` simply never existed.

> That's why it's my priority now to make reviewing PR's as efficient as possible. Unit test coverage is one of the ways of getting us there; it allows accepting changes without having to manually test everything, or risking that we'll break arbitrary things on every release.
> 
> > This started before your time, and you've done great work so far, but please understand it's unusual for me, a non-Literal employee, to get asked to add features when the actual company running this project has not done this or really even responded to the 350+ issues for months.
> 
> It's perfectly normal for FOSS contributors to be asked to make changes and/or extensions to PR's. In fact, many popular FOSS packages have rigorous standards as to what (kinds of) PR's they're willing to accept. I know there's pain in setting such standards, but I personally want to be able to rely on chainlit in production -- and this really is part of getting us there.
>
> We're hoping to fork the data layers out into a separate chainlit-community repo over the coming weeks.

Can you, or other employees, expand on the vision for Chainlit and who (Literal or External) is expected to make features? I don't think this is clear from our perspective. If we are to solve our own GitHub issues and create our own features, then I think it should be widely communicated and added to the documentation. And if this is true I wonder why split out the data layers at all when you could just give some community members contributor access with extra controls.

Sorry if this sounds weird, I have just been increasing confused by Literal's vision and involvement in Chainlit. The only "features" we've seen for the past 3 months are things nobody here or in discord are even asking for and removed core functionality. Even now some kind of "assistant" tooling is being added. Why? Who is asking for this? Why aren't any of the highly vocalized features being tackled? Of the top of my head:
- Feedback is gone for steps
- Prompt Playground is completely removed from Chainlit
- Auto-expand steps was taken away
- Step Nesting was taken away
- Markdown on home page was taken away
- Latex `$$` notation is not how LLMs were trained and difficult to fix via prompting.

Sorry for the massive de-railment here, but this is the only engagement I can get with the devs. As for this PR, it's a pretty clear solution and currently any SQLAlchemy users cannot upgrade to this import "security" upgrade in 1.2.0, so I kindly ask we include this in the next release and I look forward to a robust test suite and a reliable, feature-rich Chainlit :)

**Review by dokterbob — APPROVED** [review]

**Comment by dokterbob** [comment]
> Can you, or other employees, expand on the vision for Chainlit and who (Literal or External) is expected to make features? I don't think this is clear from our perspective. If we are to solve our own GitHub issues and create our own features, then I think it should be widely communicated and added to the documentation.

In the basis "we are to solve our own GitHub issues and create our own features" is what Open Source implies. Of course, if you'd like to pay people (Chainlit, or others) to develop features you specifically like, you can have exactly those features in exactly the way you like.

What Chainlit is clearly committed to is fostering community contributions, we really want to push overall product stability, maturity and catch up on the many PR's and issues pending. For now, the investment in battling technical debt does imply moving slower in features and a bit more energy in fixing obvious bugs and overall cleanliness, plus basic testing infra.

Some initial clarification on this seems underway in https://github.com/Chainlit/chainlit/pull/1351
As we solidify strategy more and more we will try to communicate it more clearly as well.

> Sorry if this sounds weird, I have just been increasing confused by Literal's vision and involvement in Chainlit. The only "features" we've seen for the past 3 months are things nobody here or in discord are even asking for and removed core functionality. Even now some kind of "assistant" tooling is being added. Why? Who is asking for this? Why aren't any of the highly vocalized features being tackled? Of the top of my head:
> 
> * Feedback is gone for steps
> * Prompt Playground is completely removed from Chainlit
> * Auto-expand steps was taken away
> * Step Nesting was taken away
> * Markdown on home page was taken away
> * Latex `$$` notation is not how LLMs were trained and difficult to fix via prompting.

As a software project matures, its common that it becomes apparent that supporting a large number of features and use cases is unsustainable. As that happens, features get dropped. What I am personally aiming for is to refactor chainlit to allow as much functionality to be contributed by outside contributors, in separate packages.

We attempt to foster this by a community-led repo, similar to [Django's jazzband](https://jazzband.co/), separate from a more minimal 'core product'. They can have different QOS levels, release paces, strategy and management.

> Sorry for the massive de-railment here, but this is the only engagement I can get with the devs. 

Please, join us on Discord. :)
Happy to chat there. Also coming up is Ask the Maintainers Anything to clarify doubts.

> As for this PR, it's a pretty clear solution and currently any SQLAlchemy users cannot upgrade to this import "security" upgrade in 1.2.0, so I kindly ask we include this in the next release and I look forward to a robust test suite and a reliable, feature-rich Chainlit :)

Hereby done! Now, there's a basis for testing infra which will guide you and other users to expand tests as changes/fixes come in.

**Pull request merged**
