### PR TITLE
Newly created thread displayed in the side bar; Resumed threads content is revalidated when navigating in the side bar

### PR DESCRIPTION
**Pull request by BrittleFoot**
Hi!

I recently posted two issues:
- https://github.com/Chainlit/chainlit/issues/824
- https://github.com/Chainlit/chainlit/issues/823

Here's my proposal for solving it

There are two main ideas:

- when the new thread is created we refresh the list of the threads
  > I detect it with a combination of `firstInteraction` and `messages` states, since, as mentioned in https://github.com/Chainlit/chainlit/issues/837 there is no clear way to determine a newly created thread
- when the thread is resumed - we set the current thread page data as '' with `mutate()` so it'll be invalidated on the next render.
- also, when the already resumed/opened thread is clicked in the thread history sidebar the user is redirected to this opened chat, instead of a suggestion to resume the thread again

Here's a demo of how it works

https://github.com/Chainlit/chainlit/assets/14301123/99f90677-5854-4925-b815-30c6e0dedde4

### CODE REVIEW

**Comment by tpatel** [comment]
Hello, I've tried to rebase to test these changes but made a mistake and it close the PR, I'm working on fixing it

**Comment by tpatel** [comment]
@BrittleFoot Would you mind adding me temporarily as a contributor to your fork? I believe when I updated your code it failed in the middle, close the PR which cut my access to your repo 😓 

After some testing your code has a lot of potential, I just had an issue with the thread list that is reloaded more often than it needs, which sometimes sets the `currentThreadId` to the wrong thread.

**Comment by tpatel** [comment]
After looking into your work, we decided to go with an alternative implementation, where the current chat is moved to `/thread/:id` after being persisted, instead of staying at `/`. The current PR is located at https://github.com/Chainlit/chainlit/pull/923

**Comment by BrittleFoot** [comment]
Works for me, thanks! More robust, even.

my pleasure contributing to it

**Pull request closed without merging**
