### PR TITLE
fix: socket.io upgrade sometimes happen before connect

### PR DESCRIPTION
**Pull request by sandangel**
Signed-off-by: San Nguyen <vinhsannguyen91@gmail.com>

### CODE REVIEW

**Comment by rohanbalkondekar** [comment]
@CodiumAI-Agent /describe

**Comment by sandangel** [comment]
Hi, may I ask any update to this PR?

**Comment by dokterbob** [comment]
> Hi, may I ask any update to this PR?

The description of your PR was empty, so it's hard for us to review it.

Could you please describe _in detail_:
1. What specific use case(s) it addresses or, preferably, how we might replicate this issue.
2. What the expected end result is.
3. What happens instead?
4. What reasoning led to the specific proposed solution, including possible alternatives you have considered.

Lastly, why did you remove the comments there? As this is quite a particular issue, what's the need of not having a direct reference to the context at hand?

**Comment by sandangel** [comment]
Hi, I guess we might just remove the `force websocket mode` things together. It might not work as intended. Any opinion on this?

**Comment by sandangel** [comment]
Closing. I will open a PR to revert the require websocket that I added before.

**Pull request closed without merging**
