### PR TITLE
feat: make chainlit server configurable

### PR DESCRIPTION
**Pull request by chenjuneking**
I think it's better to make chainlit server configurable, it's helpful for the privatization deployment.

### CODE REVIEW

**Review by willydouhard — APPROVED** [review]
Thank you!

**Comment by constantinidan** [comment]
Hi @chenjuneking thank you very much for your contributions! Let's connect. Can you send a dm on Discord or via linkedin?

**Comment by chenjuneking** [comment]
> Hi @chenjuneking thank you very much for your contributions! Let's connect. Can you send a dm on Discord or via linkedin?

Hi @constantinidan , Here is my linkedin profile: `https://www.linkedin.com/in/junkin-chen-3884a8148`.
I'm looking for a full-time remote job now, is it any possibility to join your team?

**Comment by constantinidan** [comment]
@chenjuneking added you on Linkedin. Let's talk there :)

**Pull request merged**
