### PR TITLE
fix URL of MS Graph API for getting currently logged-in user after Azure AD OAuth

### PR DESCRIPTION
**Pull request by triantafillos**
Based on #415

### CODE REVIEW

**Review by tpatel — APPROVED** [review]
✨✨✨ Thanks for your contribution ✨✨✨

**Comment by triantafillos** [comment]
@tpatel I have no rights to merge so I suppose someone else will do it?

**Comment by tpatel** [comment]
It's merged ✅

**Comment by triantafillos** [comment]
Thank you!

**Pull request merged**
