### PR TITLE
Bump Python requirement to 3.9. Solves #1189.

### PR DESCRIPTION
**Pull request by dokterbob**
See https://github.com/Chainlit/chainlit/issues/1189

### CODE REVIEW

**Comment by EWouters** [comment]
I had to go through this as well to get a development setup to work for #1218 on my mac. I ended up with 9ee7ca7f1effe4fce51179663b27d4d0f91e25f4.

 
<details><summary>There are a few more things in there that may be unrelated, and it still trips up the type checker in the pre-commit hook.</summary>
→ No staged files match any configured task.

> @ lintPython /Users/erik/git/chainlit
> cd backend && poetry run mypy chainlit/

chainlit/element.py:245: error: Argument 2 to "savefig" of "Figure" has incompatible type "**dict[str, object]"; expected "Optional[bool]"  [arg-type]
Found 1 error in 1 file (checked 51 source files)
 ELIFECYCLE  Command failed with exit code 1.
husky - pre-commit hook exited with code 1 (error)
</details>

**Comment by dokterbob** [comment]
@willydouhard Would love a review from you on this one, it would really improve dev experience.

**Comment by dokterbob** [comment]
@willydouhard Please approve this one so I can merge it so I can merge #1217 after.

**Comment by dokterbob** [comment]
Superseded by #1217

**Pull request closed without merging**
