### PR TITLE
Fix SQLAlchemyDataLayer in sql_alchemy.py

### PR DESCRIPTION
**Pull request by mohamedalani**
Fixing 2 bugs: 
- adding `self.storage_provider = None` in `def __init__()` so that it does not break method create_element. 

- adding generation parameter in create_step as it's also a JSON type

### CODE REVIEW

**Comment by intc-hharshtk** [comment]
THanks for the fix in sql_alchemy.py, been stuck with parameters generation.

**Comment by mohamedalani** [comment]
@hayescode @willydouhard what do you guys think?

**Review by tpatel — APPROVED** [review]
Thanks for your contribution ✨

**Comment by willydouhard** [comment]
Looks like you have a mypy issue:
```
chainlit/data/sql_alchemy.py:42: error: Incompatible types in assignment (expression has type "None", variable has type "BaseStorageClient")  [assignment]
```

**Pull request merged**
