### PR TITLE
Add token field to AppUser and function to update

### PR DESCRIPTION
**Pull request by JayRHa**
Added support to save token in the user_session and add additional scopes the EntraId toke with the optional enviroment var: OAUTH_OKTA_AUTHORIZATION_SERVER_ID

### CODE REVIEW

**Comment by JayRHa** [comment]
This would be very important for us that you merge this change

**Comment by willydouhard** [comment]
In the meantime you can add this at the beginning of your `app.py` file to override the scope:

```py
from chainlit.oauth_providers import providers, AzureADOAuthProvider


azure_provider = next((p for p in providers if isinstance(p, AzureADOAuthProvider)), None)

if azure_provider:
    azure_provider.authorize_params["scope"] = ["..."]
```

**Comment by hayescode** [comment]
I 2nd this PR, it will be very good to perform additional API calls for specific roles/priviledges, for example.

**Comment by JayRHa** [comment]
It would also be awesome if we can cail token for the scope https://database.windows.net/.default

**Comment by JayRHa** [comment]
Yes this works to get other scopes for graph api but not to get other tokens for other microsoft apis like azure or database.

**Comment by willydouhard** [comment]
I see, I agree with the concept but this will clash with the 1.0.0 release. Will revisit this in 1/2 weeks

**Comment by hayescode** [comment]
@willydouhard can we expect this in a future release? My personal goal with this is to 1) limit access to users in certain security groups and 2) give users settings/features based on security groups.

**Comment by hayescode** [comment]
> I see, I agree with the concept but this will clash with the 1.0.0 release. Will revisit this in 1/2 weeks

@willydouhard will this functionality be included in 1.0.0?

**Comment by willydouhard** [comment]
You will be able to set metadata to users and then differentiate access to users based on that metadata. The release will happen on Monday 10AM CET

**Comment by willydouhard** [comment]
Do you confirm this is fixed with the 1.0.0 release?

**Comment by JayRHa** [comment]
How does this work? Have an example

**Comment by willydouhard** [comment]
Following the [doc](https://docs.chainlit.io/authentication/oauth#allow-all-users-who-passed-the-oauth-authentication)

```py
from typing import Dict, Optional
import chainlit as cl

@cl.oauth_callback
def oauth_callback(
    provider_id: str,
    token: str,
    raw_user_data: Dict[str, str],
    default_user: cl.User,
) -> Optional[cl.User]:
    metadata = default_user.metadata.copy()
    metadata["oauth_token"] = token
    metadata["my_custom_field"] = "my_custom_value"
    return cl.User(identifier=default_user.identifier, metadata=metadata)
 ```
 
 Then you can access the user (including the metadata) in any Chainlit decorator

```py
@cl.on_chat_start
async def start():
    user = cl.user_session.get("user")  # type: cl.User
    print(user)
```

**Comment by willydouhard** [comment]
Closing this. Please reopen if the issue is not solved.

**Pull request closed without merging**
