### PR TITLE
bump python multipart to 0.0.18

### PR DESCRIPTION
**Pull request by tituslhy**
Bumping multipart dependency to resolve [feature request #1561](https://github.com/Chainlit/chainlit/issues/1561)

### CODE REVIEW

**Comment by dokterbob** [comment]
Why this consistently fails is beyond me...

**Review by dokterbob — COMMENTED** [review]
Thanks for the contrib but... this updates a lot more than just python-multipart!

Potentially causing a lot of side-effects (maybe that's why tests are failing). A patch updating python-multipart should really just be updating that.

In the end I did `poetry add 'python-multipart>=0.0.18,<0.1'`, to keep with my suggested `^0.0` but also require `>0.0.18` as there's a security issue (https://github.com/Chainlit/chainlit/security/dependabot/99).

To save both of us a bit of time, I already created the PR. https://github.com/Chainlit/chainlit/pull/1570

Love to hear your feedback though, does it solve your issue?

**Comment by dokterbob** [comment]
Superseded by #1570

**Comment by tituslhy** [comment]
Yes it does! The failing tests are weird. I only updated the pyproject.toml file and later just ran `poetry lock` and checked in both the pyproject.toml and poetry.lock file. I think the locking process caused Python to automatically update the rest of the dependencies which caused the tests to fail.

Thanks @dokterbob!

**Pull request closed without merging**
