### PR TITLE
Refactor socket.py to handle task interruption gracefully

### PR DESCRIPTION
**Pull request by jpolvto**
When the user presses the stop button, the backend raises an InterruptedError. In my mind this should be logged instead. Let me know if I've missed something!

### CODE REVIEW

**Comment by jpolvto** [comment]
Will fix the test.

**Comment by willydouhard** [comment]
Then it won't actually stop the task I believe. Currently it is the error that will interrupt an async task

**Comment by jasperpolaxinter** [comment]
This is solved in the latest version, so I'll remove the pull request

**Comment by jpolvto** [comment]
This is resolved in the latest version, I'll close the pull request

**Pull request closed without merging**
