### PR TITLE
fix: websocket connection when submounting chainlit

### PR DESCRIPTION
**Pull request by willydouhard**
Running this [example](https://docs.chainlit.io/integrations/fastapi) currently fails (websocket connection fails). This is an attempt to better submount chainlit and fix this issue.

### CODE REVIEW

**Comment by sandangel** [comment]
Will this approach have issue with `router` prefix? So sending request to `/app-root` will now become `/app-root/app-root`?

**Comment by dokterbob** [comment]
> Will this approach have issue with `router` prefix? So sending request to `/app-root` would become `/app-root/app-root`?

Unlikely but we'd love some feedback from users on this, as there's such a large variety of use cases.

**Comment by willydouhard** [comment]
The router is [no longer prefixed](https://github.com/Chainlit/chainlit/pull/1337/files#diff-9a73e67e163edc3fae6839bf2bcc8c6ab650624eff6668502388a7a86b7ece78L195) so it should be fine imo

**Comment by dokterbob** [comment]
Good step towards #1223!

**Comment by willydouhard** [comment]
I tested this PR with different scenarios:
1. Submounting the application to a parent Fast API app (including with oauth redirections)
2. Starting Chainlit with `--root-path`
3. Starting Chainlit normally

**Comment by dokterbob** [comment]
### Testing in progresss

- [ ] Mounted in FastAPI app
- [ ] Example from docs (https://github.com/Chainlit/docs/issues/172)
- [ ] Cookbook example (https://github.com/Chainlit/cookbook/issues/137)
- [ ] https://github.com/Chainlit/chainlit/issues/1313
- [ ] https://github.com/Chainlit/chainlit/issues/1317
- [ ] https://github.com/Chainlit/chainlit/issues/1330

**Review by dokterbob — APPROVED** [review]
Let's gooo!

**Pull request merged**
